### ISSUE TITLE
Missing code in 4.8.7.1 release of __init__.py in axiom_tc

### ISSUE THREAD

**Issue by BA52Git** [TouchNetix/axiom_pylib#28]
The 4.8.7.1 release of axiom_tc has an outdated definition of  __ all __ in the script __ init __ .py causing issues with the USB_Comms.  

Using the main branch of the __init__.py will solve the issue.

**Comment by marksat** [comment]
Hey @BA52Git - I have released v4.8.7.2 onto [pypi](https://pypi.org/project/axiom-tc/) which should address this issue. Please update the axiom_tc module in pip and pull the latest changes to axutils and they should all by synced together.

I will close this ticket, but feel free to reopen if you still have an issue.
