### ISSUE TITLE
How to read the data from the Axiom device using python?

### ISSUE THREAD

**Issue by aakash-chakraborty1995** [TouchNetix/axiom_pylib#8]
I need to read the data that the axiom touchpad is throwing but only a part of the data I am receiving with the help of pywinusb library. I have connected the device via usb.

**Comment by aakash-chakraborty1995** [comment]
I need to read the data that the axiom touchpad is throwing but only a part of the data I am receiving with the help of pywinusb library. I have connected the device via usb.

**Comment by marksat** [comment]
Hi,

Are you able to provide more details?

We use the python package `hid` to handle the low level USB comms. If you are on Windows, it is a little more involved to setup. Refer to the [USB Interface](https://github.com/TouchNetix/axiom_pylib#usb-interface) section of the README.md.

If you are running on Linux, you may have to be a super user to access the USB interface.

Best Regards, Mark

**Comment by aakash-chakraborty1995** [comment]
I want to read the data from the touch pad device in Windows OS and there are two types of data. 
1. Touchnetix Press Data
2. Touchnetix Control Data
[https://github.com/rene-aguirre/pywinusb/blob/master/examples/raw_data.py]
I have used the above mentioned script and able to read the press data but whenever I have tried to read the control data it is not throwing me anything. After some research it seems I need to send some data to the device to establish a connection over usb and then maybe I can get the data. 
So, any help from your side is very much appreciated.

**Comment by Jimmy-Cameron** [comment]
As you have found, the USB bridge has multiple interfaces:
- TBP Control
- TBP Press
- (Digitizer - if enabled)

After a reset, the bridge will start sending data to the Press interface without the host needing to send any requests/commands. The data coming from this interface contains XYZ information for up to 5 targets.

To get the bridge to send data to the Control interface, the host needs to send a command to put the bridge into what we call Proxy mode. In this mode, the bridge will autonomously read all reports from aXiom (from u34) and send these to the host.

To put the bridge into this mode, [this function](https://github.com/TouchNetix/axiom_pylib/blob/01d27812ef1e8fdfb56e8df0e9af700908774eca/axiom_tc/USB_Comms.py#L284) can be called.

As a simple example, it can be used as follows:
```Python
from axiom_tc import axiom
from axiom_tc.USB_Comms import USB_Comms

usb = USB_Comms()
ax = axiom(usb)
usb.set_proxy_mode()
```

**Comment by marksat** [comment]
@aakash-chakraborty1995 is your issue resolved?

**Comment by aakash-chakraborty1995** [comment]
Thanks a lot. The issue got resolved.
